name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        target:
          - inemom1/accelero
          - inemom1/gyro
          - inemom1/leds
          - inemom1/pwm
          - stm32f4discovery/accel
          - stm32f4discovery/audio
          - stm32f4discovery/leds
          - stm32f4discovery/skel
          - stm32f4discovery/timerirq
          - stm32f429discovery/adcdma
          - stm32f429discovery/adcpolling
          - stm32f429discovery/button
          - stm32f429discovery/gyro
          - stm32f429discovery/leds
          - stm32f429discovery/spimaster
          - stm32f429discovery/spislave
          - stm32f429discovery/timerirq
          - stm32f429discovery/timerpwm
          - mbed-lpc1768/leds

    container:
      image: grumpycoders/uc-sdk-build-env:latest
      env:
        TARGET: ${{matrix.target}}

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make -C examples/$TARGET
