# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

strategy:
  matrix:
    target:
      - inemom1/accelero
      - inemom1/gyro
      - inemom1/leds
      - inemom1/pwm
      - stm32f4discovery/accel
      - stm32f4discovery/audio
      - stm32f4discovery/leds
      - stm32f4discovery/skel
      - stm32f4discovery/timerirq
      - stm32f429discovery/adcdma
      - stm32f429discovery/adcpolling
      - stm32f429discovery/button
      - stm32f429discovery/gyro
      - stm32f429discovery/leds
      - stm32f429discovery/spimaster
      - stm32f429discovery/spislave
      - stm32f429discovery/timerirq
      - stm32f429discovery/timerpwm
      - mbed-lpc1768/leds

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    container:
      image: grumpycoders/uc-sdk-build-env:latest
      env:
        TARGET: ${{matrix.target}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build
      run: make -C /uC-sdk/examples/$TARGET
